#+TITLE: Architecture Project 1
#+AUTHOR: Kevin Orr
#+DATE: June 25, 2017

#+OPTIONS: toc:nil
#+LATEX_HEADER: \usepackage{multirow}
#+LATEX_HEADER: \renewcommand{\thesubsection}{\alph{subsection})}
#+LATEX_HEADER: \renewcommand{\thesubsubsection}{\alph{subsubsection})}

* ALPHA
** Benchmark Results
   #+BEGIN_EXPORT latex
   \begin{table}[htb]
   \begin{center}
   \begin{tabular}{|c|c|c|c|c|c|c|c|}
     \hline
     \multirow{3}{*}{Benchmark} & \multirow{3}{*}{Instructions} & \multicolumn{6}{c|}{Instruction Distribution} \\ \cline{3-8}
     & & \multirow{2}{*}{Load} & \multirow{2}{*}{Store} & Uncond & Cond   & Integer  & FP\\
     & &                       &                        & Branch & Branch & Comp     & Comp \\
     \hline
     \texttt{anagram.alpha} & 4940 & 18.24\% & 19.64\% & 6.30\% & 11.76\% & 43.59\% & 0.18\% \\
     \texttt{go.alpha} & 545823087 & 30.62\% & 8.17\% & 2.58\% & 10.96\% & 47.64\% & 0.03\% \\
     \texttt{compress95.alpha} & 88981 & 1.80\% & 78.53\% & 0.28\% & 5.76\% & 13.62\% & 0.00\% \\
     \texttt{cc1.alpha} & 337353488 & 24.67\% & 11.47\% & 4.12\% & 13.33\% & 46.30\% & 0.11\% \\
     \hline
   \end{tabular}
   \end{center}
   \end{table}
   #+END_EXPORT

** Is the benchmark memory- or computationally-intensive?
*** ~anagram.alpha~
    ~38% of the instructions are memory operations, and the rest are computational. This benchmark is mostly computationally-intensive.
*** ~go.alpha~
    This benchmark has the same approximate memory/computation ration as ~anagram.alpha~, so it is mostly computationally-intensive.
*** ~compress95.alpha~
    This benchmark has ~80% memory operations; it is mostly memory-intensive.
*** ~cc1.alpha~
    This benchmark has only ~36% memory operations, with the rest computational. This is computationally-intensive.

** Is the benchmark mainly using integer or floating point computations?
*** ~anagram.alpha~
    43.59% Integer vs 0.18% FP, so FP.
*** ~go.alpha~
    47.64% Integer vs 0.03% FP, so FP.
*** ~compress95.alpha~
    13.62% Integer vs 0.00% FP, so FP.
*** ~cc1.alpha~
    46.30% Integer vs 0.11% FP, so FP.

** What % of the instructions executed are conditional branches? How many instructions are computed between each pair of conditional branches?
*** ~anagram.alpha~
    11.76%. \Sigma(18.24%, 19.64%, 6.30%, 43.59%, 0.18%)/11.76% = 7.48
*** ~go.alpha~
    10.96%. \Sigma(30.62%, 8.17%, 2.58%, 47.64%, 0.03%)/10.96% = 8.12
*** ~compress95.alpha~
    5.76%. \Sigma(1.80%, 78.53%, 0.28%, 13.62%, 0.00%)/5.76% = 16.36
*** ~cc1.alpha~
    4.12%. \Sigma(24.67%, 11.47%, 13.33%, 46.30%, 0.11%)/4.12% = 23.25

* Alpha vs PISA
** ALPHA Benchmark Results
   #+BEGIN_EXPORT latex
   \begin{table}[htb]
   \begin{center}
   \begin{tabular}{|c|c|c|c|c|c|c|c|}
     \hline
     \multirow{3}{*}{Benchmark} & \multirow{3}{*}{Instructions} & \multicolumn{6}{c|}{Instruction Distribution} \\ \cline{3-8}
     & & \multirow{2}{*}{Load} & \multirow{2}{*}{Store} & Uncond & Cond   & Integer  & FP\\
     & &                       &                        & Branch & Branch & Comp     & Comp \\
     \hline
     \texttt{test-math} & 49310 & 17.14\% & 10.44\% & 3.95\% & 11.03\% & 55.40\% & 1.88\% \\
     \texttt{test-fmath} & 19399 & 17.64\% & 12.58\% & 4.72\% & 11.17\% & 53.29\% & 0.43\% \\
     \texttt{test-llong} & 10527 & 17.66\% & 14.73\% & 5.47\% & 12.21\% & 49.63\% & 0.10\% \\
     \texttt{test-printf} & 983373 & 17.99\% & 10.74\% & 4.82\% & 11.39\% & 54.85\% & 0.09\% \\
     \hline
   \end{tabular}
   \end{center}
   \end{table}
   #+END_EXPORT

** PISA
   #+BEGIN_EXPORT latex
   \begin{table}[htb]
   \begin{center}
   \begin{tabular}{|c|c|c|c|c|c|c|c|}
     \hline
     \multirow{3}{*}{Benchmark} & \multirow{3}{*}{Instructions} & \multicolumn{6}{c|}{Instruction Distribution} \\ \cline{3-8}
     & & \multirow{2}{*}{Load} & \multirow{2}{*}{Store} & Uncond & Cond   & Integer  & FP\\
     & &                       &                        & Branch & Branch & Comp     & Comp \\
     \hline
     \texttt{test-math} & 213553 & 15.96\% & 10.67\% & 4.22\% & 13.84\% & 54.42\% & 0.88\% \\
     \texttt{test-fmath} & 53312 & 16.17\% & 14.47\% & 4.24\% & 15.08\% & 49.90\% & 0.11\% \\
     \texttt{test-llong} & 29495 & 16.38\% & 18.11\% & 4.37\% & 15.40\% & 45.70\% & 0.00\% \\
     \texttt{test-printf} & 1813745 & 19.22\% & 9.28\% & 5.13\% & 17.01\% & 49.33\% & 0.01\% \\
     \hline
   \end{tabular}
   \end{center}
   \end{table}
   #+END_EXPORT
   
** Comparison
   The PISA ISA requires many more (1.8x - 4.3x) instructions than the \mbox{ALPHA} ISA for the same programs.
